---
- name: install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - nmap
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: add docker ce repo key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker ce repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    filename: docker
    update_cache: true

- name: install docker-ce
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: determine swarm status
  become: true
  shell: >
    docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: swarm_status

- name: initialize swarm cluster
  become: true
  shell: >
    docker swarm init
    --advertise-addr={{ ansible_default_ipv4.address | default('eth0') }}:2377
  when: "'inactive' in swarm_status.stdout_lines"
